"""Windows integration: shortcuts, icons, CLI commands, PATH, claude:// handler, tray agent."""

import json
import os
import shutil
from pathlib import Path
from typing import List, Optional

import winreg

from ..core import icons, paths
from . import claude_app, winutil

START_MENU_FOLDER = "Claude Profiles"
LOADER_TITLE = "Claude Loader"
WRAPPER_MARKER = "rem Generated by claude-profiles."
MANIFEST = paths.DATA_DIR / "shortcuts.json"   # Desktop shortcuts we created
AGENT_MUTEX = "ClaudeProfilesAgent"
AGENT_STOP = paths.DATA_DIR / "agent.stop"
URL_KEY = r"Software\Classes\claude"
URL_COMMAND_KEY = URL_KEY + r"\shell\open\command"


# --- locations --------------------------------------------------------------------

def start_menu_dir() -> Path:
    return winutil.known_folder("Programs") / START_MENU_FOLDER


def startup_shortcut() -> Path:
    return winutil.known_folder("Startup") / "Claude Profiles.lnk"


def _old_startup_shortcut() -> Path:  # name used by 0.2.0
    return winutil.known_folder("Startup") / "Claude Profiles Agent.lnk"


def needs_startup(cfg) -> bool:
    agent = cfg.loader.enabled and cfg.loader.tray
    loader = cfg.loader.enabled and cfg.loader.open_at_login
    return bool(agent or loader or cfg.autostart_profiles)


def desktop_dir() -> Path:
    return winutil.known_folder("Desktop")


def shortcut_name(profile) -> str:
    safe = "".join(c for c in profile.name if c not in '<>:"/\\|?*').strip() or profile.id
    return f"Claude ({safe}).lnk"


def icon_base(profile) -> Path:
    # The color is part of the name so Explorer's icon cache notices a change.
    return paths.ICON_DIR / f"{profile.id}-{profile.color}"


def icon_ico(profile) -> Path:
    return icon_base(profile).with_suffix(".ico")


def icon_png(profile) -> Path:
    return icon_base(profile).with_suffix(".png")


def loader_ico() -> Path:
    return paths.ICON_DIR / "loader.ico"


def loader_png() -> Path:
    return paths.ICON_DIR / "loader.png"


def _module_args(*args: str) -> str:
    return " ".join(["-m", "claude_profiles.windows"] + [f'"{a}"' if " " in a else a for a in args])


# --- icons -----------------------------------------------------------------------------

def _base_image() -> Path:
    """The Claude logo scaled to 256 px once; recoloring starts from this file."""
    base = paths.ICON_DIR / "base.png"
    if not base.exists():
        src = claude_app.find_icon()
        paths.ICON_DIR.mkdir(parents=True, exist_ok=True)
        try:
            if not src:
                raise FileNotFoundError
            img = icons.resize(icons.load_image(src), icons.SIZE)
        except Exception:
            img = icons.fallback_disc(icons.cfgmod.COLORS["original"][3])
        base.write_bytes(icons.encode_png(img))
    return base


def build_icons(cfg) -> None:
    base = str(_base_image())
    wanted = {paths.ICON_DIR / "base.png"}
    for p in cfg.profiles:
        for dst, size in ((icon_ico(p), icons.SIZE), (icon_png(p), 96)):
            wanted.add(dst)
            if not dst.exists():
                icons.make_icon(base, p.color, dst, size)
    for dst, size in ((loader_ico(), icons.SIZE), (loader_png(), 96)):
        wanted.add(dst)
        if not dst.exists():
            icons.make_icon(base, "original", dst, size)
    for f in paths.ICON_DIR.glob("*.*"):
        if f not in wanted:
            try:
                f.unlink()
            except OSError:
                pass


def rebuild_icons() -> None:
    if paths.ICON_DIR.exists():
        shutil.rmtree(paths.ICON_DIR, ignore_errors=True)


# --- shortcuts -----------------------------------------------------------------------------

def _load_manifest() -> List[str]:
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []


def _save_manifest(items: List[str]) -> None:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(items, indent=1), encoding="utf-8")


def write_shortcuts(cfg) -> None:
    pyw = winutil.pythonw()
    workdir = str(paths.APP_DIR if paths.APP_DIR.exists() else paths.HOME)
    menu = start_menu_dir()
    items, keep_menu = [], set()

    def add(path: Path, args: str, icon: Path, description: str):
        items.append({"path": path, "target": pyw, "args": args, "icon": icon,
                      "workdir": workdir, "description": description})

    for p in cfg.profiles:
        name = shortcut_name(p)
        keep_menu.add(name.lower())
        add(menu / name, _module_args("launch", p.id), icon_ico(p),
            f'Claude Desktop, profile "{p.name}"')
    if cfg.loader.enabled:
        keep_menu.add(f"{LOADER_TITLE}.lnk".lower())
        add(menu / f"{LOADER_TITLE}.lnk", _module_args("loader"), loader_ico(),
            "Pick and launch your Claude profiles")

    desktop_items = []
    if cfg.desktop_shortcuts:
        desk = desktop_dir()
        for p in cfg.profiles:
            path = desk / shortcut_name(p)
            desktop_items.append(str(path))
            add(path, _module_args("launch", p.id), icon_ico(p),
                f'Claude Desktop, profile "{p.name}"')

    winutil.create_shortcuts(items)

    # Everything in our Start Menu folder is ours; on the Desktop only what we recorded.
    if menu.exists():
        for f in menu.glob("*.lnk"):
            if f.name.lower() not in keep_menu:
                f.unlink()
    for old in _load_manifest():
        if old not in desktop_items:
            try:
                Path(old).unlink()
            except OSError:
                pass
    _save_manifest(desktop_items)


def remove_shortcuts() -> None:
    menu = start_menu_dir()
    if menu.exists():
        shutil.rmtree(menu, ignore_errors=True)
    for old in _load_manifest():
        try:
            Path(old).unlink()
        except OSError:
            pass
    if MANIFEST.exists():
        MANIFEST.unlink()


# --- CLI wrappers ------------------------------------------------------------------------------

def _cmd_path(path: str) -> str:
    """Write paths under %LOCALAPPDATA% with the variable: .cmd files are read in the
    console code page, which may not be able to spell a non-ASCII user name."""
    base = str(paths.LOCALAPPDATA)
    if path.lower().startswith(base.lower() + os.sep):
        return "%LOCALAPPDATA%" + path[len(base):]
    return path


def write_cli_wrappers(cfg) -> None:
    paths.BIN_DIR.mkdir(parents=True, exist_ok=True)
    python = _cmd_path(winutil.python_console())
    keep = set()
    for p in cfg.profiles:
        if not p.cli:
            continue
        path = paths.BIN_DIR / f"{p.cli_command}.cmd"
        if path.exists() and WRAPPER_MARKER not in path.read_text(encoding="utf-8", errors="ignore"):
            continue  # never overwrite something we did not create
        keep.add(path.name.lower())
        # Text mode turns "\n" into CRLF on Windows.
        path.write_text("@echo off\n"
                        f"{WRAPPER_MARKER} Claude Code CLI with the \"{p.name}\" profile.\n"
                        f"\"{python}\" -m claude_profiles.windows cli {p.id} -- %*\n",
                        encoding="utf-8")
    for f in paths.BIN_DIR.glob("claude-*.cmd"):
        if f.name.lower() in keep:
            continue
        try:
            if WRAPPER_MARKER in f.read_text(encoding="utf-8", errors="ignore"):
                f.unlink()
        except OSError:
            pass


def remove_cli_wrappers() -> None:
    if paths.BIN_DIR.exists():
        for f in paths.BIN_DIR.glob("claude-*.cmd"):
            try:
                if WRAPPER_MARKER in f.read_text(encoding="utf-8", errors="ignore"):
                    f.unlink()
            except OSError:
                pass


# --- claude:// handler ---------------------------------------------------------------------------

def our_url_command() -> str:
    return f'"{winutil.pythonw()}" {_module_args("open-url")} "%1"'


def current_url_command() -> Optional[str]:
    return winutil.reg_get(winreg.HKEY_CURRENT_USER, URL_COMMAND_KEY)


def url_handler_is_ours() -> bool:
    cmd = current_url_command() or ""
    return "claude_profiles.windows" in cmd


def enable_url_handler(cfg) -> None:
    """Point claude:// at our router. Claude re-registers itself when it starts,
    so the tray agent calls this again whenever the value changes."""
    current = current_url_command()
    if current and "claude_profiles.windows" not in current:
        cfg.previous_url_handler = current
    winutil.reg_set(winreg.HKEY_CURRENT_USER, URL_KEY, "", "URL:claude")
    winutil.reg_set(winreg.HKEY_CURRENT_USER, URL_KEY, "URL Protocol", "")
    winutil.reg_set(winreg.HKEY_CURRENT_USER, URL_COMMAND_KEY, "", our_url_command())


def disable_url_handler(cfg) -> None:
    if not url_handler_is_ours():
        return
    previous = (cfg.previous_url_handler if cfg else None)
    if not previous:
        exe = claude_app.installed_exe()
        previous = f'"{exe}" "%1"' if exe else None
    if previous:
        winutil.reg_set(winreg.HKEY_CURRENT_USER, URL_COMMAND_KEY, "", previous)
    else:
        winutil.reg_delete_tree(winreg.HKEY_CURRENT_USER, URL_KEY)


# --- tray agent ------------------------------------------------------------------------------------

def agent_running() -> bool:
    return winutil.mutex_exists(AGENT_MUTEX)


def start_agent() -> None:
    if AGENT_STOP.exists():
        AGENT_STOP.unlink()
    if not agent_running():
        winutil.start_detached([winutil.pythonw(), "-m", "claude_profiles.windows", "agent"],
                               cwd=str(paths.HOME))


def stop_agent() -> None:
    if agent_running():
        AGENT_STOP.parent.mkdir(parents=True, exist_ok=True)
        AGENT_STOP.write_text("stop", encoding="utf-8")


def write_startup(enabled: bool) -> None:
    """One Startup-folder shortcut runs `autostart`: chosen profiles, the loader,
    then it stays as the tray agent (if that is on)."""
    old = _old_startup_shortcut()
    if old.exists():
        old.unlink()
    link = startup_shortcut()
    if enabled:
        winutil.create_shortcuts([{"path": link, "target": winutil.pythonw(),
                                   "args": _module_args("autostart"), "icon": loader_ico(),
                                   "workdir": str(paths.HOME),
                                   "description": "Claude profiles: sign-in autostart, hotkey "
                                                  "and tray menu"}])
    elif link.exists():
        link.unlink()


# --- apply / remove ----------------------------------------------------------------------------------

def apply(cfg, start_agent_now: bool = True) -> List[str]:
    warnings = []
    for p in cfg.profiles:
        if not p.system_default:
            Path(p.data_dir).mkdir(parents=True, exist_ok=True)
    build_icons(cfg)
    try:
        write_shortcuts(cfg)
    except OSError as e:
        warnings.append(str(e))
    write_cli_wrappers(cfg)

    if cfg.path_added:
        try:
            winutil.add_to_user_path(paths.BIN_DIR)
        except OSError as e:
            warnings.append(f"Could not add {paths.BIN_DIR} to PATH: {e}")

    if cfg.url_handler:
        try:
            enable_url_handler(cfg)
        except OSError as e:
            warnings.append(f"Could not register the claude:// handler: {e}")
    else:
        disable_url_handler(cfg)

    agent_wanted = cfg.loader.enabled and cfg.loader.tray
    try:
        write_startup(needs_startup(cfg))
    except OSError as e:
        warnings.append(str(e))
    if agent_wanted and start_agent_now:
        start_agent()
    elif not agent_wanted:
        stop_agent()
    if cfg.loader.enabled and cfg.loader.hotkey and not cfg.loader.tray:
        warnings.append("The hotkey needs the tray agent, which is turned off.")
    return warnings


def remove_all(cfg) -> None:
    stop_agent()
    try:
        write_startup(False)
    except OSError:
        pass
    remove_shortcuts()
    remove_cli_wrappers()
    if cfg is not None:
        disable_url_handler(cfg)
        if cfg.path_added:
            try:
                winutil.remove_from_user_path(paths.BIN_DIR)
            except OSError:
                pass
    rebuild_icons()
