"""Linux desktop integration: menu entries, icons, CLI commands, hotkey, claude:// handler."""

import ast
import os
import re
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional

from ..core import icons, paths
from . import system

APPLICATIONS_DIR = paths.XDG_DATA / "applications"
MARKER = "X-Claude-Profiles=true"
WRAPPER_MARKER = "# Generated by claude-profiles."
LOADER_APP_ID = "io.github.claudeprofiles.Loader"
USAGE_APP_ID = "io.github.claudeprofiles.Usage"
# Named after the GTK application id so GNOME matches the window to this entry.
LOADER_ENTRY = f"{LOADER_APP_ID}.desktop"
USAGE_ENTRY = f"{USAGE_APP_ID}.desktop"
URL_ENTRY = "claude-profiles-url.desktop"
URL_MIME = "x-scheme-handler/claude"

MEDIA_KEYS = "org.gnome.settings-daemon.plugins.media-keys"
KEYBINDING = "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
KEYBINDING_PATH = "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/claude-profiles-loader/"

HOTKEY_RE = re.compile(r"^(<(Super|Shift|Control|Ctrl|Primary|Alt|Meta|Hyper)>)+[A-Za-z0-9_]+$")
# A shortcut is between two and four keys: one to three modifiers and one key.
MIN_KEYS, MAX_KEYS = 2, 4
# Shift on its own is not enough: it would swallow ordinary typing.
REAL_MODIFIERS = {"super", "control", "ctrl", "primary", "alt", "meta", "hyper"}


# --- helpers --------------------------------------------------------------------

def _exec_arg(arg: str) -> str:
    """Quote one argument for a .desktop Exec line."""
    if re.fullmatch(r"[A-Za-z0-9_@%+=:,./-]+", arg):
        return arg
    return '"' + re.sub(r'(["`$\\])', r"\\\1", arg) + '"'


def _exec_line(*args: str) -> str:
    return " ".join(_exec_arg(a) for a in args)


def _entry_text(**fields) -> str:
    lines = ["[Desktop Entry]"]
    for k, v in fields.items():
        if v is None:
            continue
        if isinstance(v, bool):
            v = "true" if v else "false"
        lines.append(f"{k}={v}")
    lines.append(MARKER)
    return "\n".join(lines) + "\n"


def _write(path: Path, text: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    os.chmod(path, mode)


def _quiet(cmd: List[str]) -> Optional[subprocess.CompletedProcess]:
    if not shutil.which(cmd[0]):
        return None
    try:
        return subprocess.run(cmd, text=True, capture_output=True, timeout=15)
    except (OSError, subprocess.TimeoutExpired):
        return None


def profile_entry_path(profile_id: str) -> Path:
    return APPLICATIONS_DIR / f"claude-profile-{profile_id}.desktop"


def icon_path(profile) -> Path:
    # The color is part of the name so icon caches notice a change.
    return paths.ICON_DIR / f"{profile.id}-{profile.color}.png"


def loader_icon_path() -> Path:
    return paths.ICON_DIR / "loader.png"


# --- icons ------------------------------------------------------------------------

def build_icons(cfg) -> None:
    src = system.find_icon()
    wanted = {icon_path(p) for p in cfg.profiles} | {loader_icon_path()}
    for p in cfg.profiles:
        dst = icon_path(p)
        if not dst.exists():
            icons.make_icon(src, p.color, dst)
    if not loader_icon_path().exists():
        icons.make_icon(src, "original", loader_icon_path())
    if paths.ICON_DIR.exists():
        for f in paths.ICON_DIR.glob("*.png"):
            if f not in wanted:
                f.unlink()


def rebuild_icons() -> None:
    """Force regeneration, e.g. after Claude Desktop changed its icon."""
    if paths.ICON_DIR.exists():
        shutil.rmtree(paths.ICON_DIR)


# --- menu entries -------------------------------------------------------------------

def write_profile_entries(cfg) -> None:
    main = str(paths.MAIN_CMD)
    for p in cfg.profiles:
        _write(profile_entry_path(p.id), _entry_text(
            Type="Application",
            Name=f"Claude ({p.name})",
            GenericName="AI assistant",
            Comment=f'Claude Desktop, profile "{p.name}"',
            Exec=_exec_line(main, "launch", p.id),
            Icon=str(icon_path(p)),
            Terminal=False,
            Categories="Development;Office;",
            StartupWMClass=p.window_class,
            StartupNotify=True,
        ))
    keep = {profile_entry_path(p.id).name for p in cfg.profiles}
    for f in APPLICATIONS_DIR.glob("claude-profile-*.desktop"):
        if f.name not in keep and MARKER in f.read_text(encoding="utf-8", errors="ignore"):
            f.unlink()


def write_loader_entry(cfg) -> None:
    path = APPLICATIONS_DIR / LOADER_ENTRY
    if not cfg.loader.enabled:
        if path.exists():
            path.unlink()
        return
    _write(path, _entry_text(
        Type="Application",
        Name="Claude Loader",
        Comment="Pick and launch your Claude profiles",
        Exec=_exec_line(str(paths.MAIN_CMD), "loader"),
        Icon=str(loader_icon_path()),
        Terminal=False,
        Categories="Development;Office;",
        StartupWMClass=LOADER_APP_ID,
        StartupNotify=True,
    ))


def write_usage_entry(cfg) -> None:
    path = APPLICATIONS_DIR / USAGE_ENTRY
    if not cfg.profiles:
        if path.exists():
            path.unlink()
        return
    _write(path, _entry_text(
        Type="Application",
        Name="Claude Token Usage",
        Comment="How much of each profile's limit is gone, and when it resets",
        Exec=_exec_line(str(paths.MAIN_CMD), "usage"),
        Icon=str(loader_icon_path()),
        Terminal=False,
        Categories="Development;Office;",
        StartupWMClass=USAGE_APP_ID,
        StartupNotify=True,
    ))


AUTOSTART_FILE = paths.XDG_CONFIG / "autostart" / "claude-profiles.desktop"


def write_autostart(cfg) -> None:
    """~/.config/autostart entry that runs `claude-profiles autostart` at sign-in."""
    wanted = (cfg.loader.enabled and cfg.loader.open_at_login) or bool(cfg.autostart_profiles)
    if not wanted:
        if AUTOSTART_FILE.exists():
            AUTOSTART_FILE.unlink()
        return
    _write(AUTOSTART_FILE, _entry_text(
        Type="Application",
        Name="Claude profiles autostart",
        Comment="Starts the Claude profiles and the loader you chose",
        Exec=_exec_line(str(paths.MAIN_CMD), "autostart"),
        Icon=str(loader_icon_path()),
        Terminal=False,
        NoDisplay=True,
        **{"X-GNOME-Autostart-enabled": True, "X-GNOME-Autostart-Delay": "3"},
    ))


def write_cli_wrappers(cfg) -> None:
    paths.BIN_DIR.mkdir(parents=True, exist_ok=True)
    keep = set()
    for p in cfg.profiles:
        if not p.cli:
            continue
        path = paths.BIN_DIR / p.cli_command
        if path.exists() and WRAPPER_MARKER not in path.read_text(encoding="utf-8", errors="ignore"):
            continue  # never overwrite something we did not create
        keep.add(path.name)
        _write(path, (
            "#!/bin/sh\n"
            f"{WRAPPER_MARKER} Claude Code CLI with the \"{p.name}\" profile.\n"
            f"exec {shlex.quote(str(paths.MAIN_CMD))} cli {shlex.quote(p.id)} -- \"$@\"\n"
        ), 0o755)
    for f in paths.BIN_DIR.glob("claude-*"):
        if f.name in keep or not f.is_file():
            continue
        try:
            if WRAPPER_MARKER in f.read_text(encoding="utf-8", errors="ignore"):
                f.unlink()
        except (OSError, UnicodeDecodeError):
            pass


def refresh_desktop_database() -> None:
    _quiet(["update-desktop-database", str(APPLICATIONS_DIR)])


# --- claude:// handler ------------------------------------------------------------------

def current_url_handler() -> Optional[str]:
    r = _quiet(["xdg-mime", "query", "default", URL_MIME])
    if not r or r.returncode != 0:
        return None
    return r.stdout.strip() or None


def _set_url_handler(entry_name: str) -> bool:
    for cmd in (["xdg-mime", "default", entry_name, URL_MIME],
                ["gio", "mime", URL_MIME, entry_name]):
        r = _quiet(cmd)
        if r and r.returncode == 0:
            return True
    return False


def enable_url_handler(cfg) -> bool:
    _write(APPLICATIONS_DIR / URL_ENTRY, _entry_text(
        Type="Application",
        Name="Claude profile link router",
        Comment="Sends claude:// sign-in links to the right Claude profile",
        Exec=_exec_line(str(paths.MAIN_CMD), "open-url") + " %u",
        Icon=str(loader_icon_path()),
        Terminal=False,
        NoDisplay=True,
        MimeType=f"{URL_MIME};",
    ))
    refresh_desktop_database()
    previous = current_url_handler()
    if previous and previous != URL_ENTRY:
        cfg.previous_url_handler = previous
    return _set_url_handler(URL_ENTRY)


def disable_url_handler(cfg) -> None:
    path = APPLICATIONS_DIR / URL_ENTRY
    if current_url_handler() == URL_ENTRY:
        entry = cfg.previous_url_handler or (
            os.path.basename(system.package_desktop_entry() or "") or None)
        if entry:
            _set_url_handler(entry)
    if path.exists():
        path.unlink()
        refresh_desktop_database()


# --- GNOME hotkey -------------------------------------------------------------------------

def _gvariant_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _keybinding_list() -> Optional[List[str]]:
    r = _quiet(["gsettings", "get", MEDIA_KEYS, "custom-keybindings"])
    if not r or r.returncode != 0:
        return None
    text = r.stdout.strip()
    if text.startswith("@as"):
        text = text[3:].strip()
    try:
        value = ast.literal_eval(text)
    except (ValueError, SyntaxError):
        return None
    return [str(v) for v in value]


def _set_keybinding_list(items: List[str]) -> bool:
    value = "[" + ", ".join(_gvariant_str(i) for i in items) + "]"
    r = _quiet(["gsettings", "set", MEDIA_KEYS, "custom-keybindings", value])
    return bool(r and r.returncode == 0)


def hotkey_problem(accel: Optional[str]) -> Optional[str]:
    """Why this shortcut cannot be used, in one sentence. None means it is fine."""
    if not accel:
        return "Press a key combination."
    if not HOTKEY_RE.match(accel):
        return "Write it in the GNOME form, for example <Super><Shift>c."
    mods = [m.lower() for m in re.findall(r"<([^>]+)>", accel)]
    keys = len(mods) + 1
    if keys < MIN_KEYS:
        return f"Use at least {MIN_KEYS} keys, for example <Control><Alt>c."
    if keys > MAX_KEYS:
        return f"Use at most {MAX_KEYS} keys."
    if len(set(mods)) != len(mods):
        return "The same modifier is used twice."
    if not set(mods) & REAL_MODIFIERS:
        return "Add Super, Ctrl or Alt - Shift on its own would swallow normal typing."
    return None


def valid_hotkey(accel: str) -> bool:
    return hotkey_problem(accel) is None


def hotkey_label(accel: Optional[str]) -> str:
    if not accel:
        return "none"
    mods = re.findall(r"<([^>]+)>", accel)
    key = re.sub(r"<[^>]+>", "", accel)
    names = {"Control": "Ctrl", "Primary": "Ctrl"}
    return "+".join([names.get(m, m) for m in mods] + [key.upper() if len(key) == 1 else key])


def set_hotkey(accel: Optional[str]) -> bool:
    """Register (or with None, remove) the GNOME shortcut that opens the loader."""
    items = _keybinding_list()
    if items is None:
        return False
    if not accel:
        if KEYBINDING_PATH in items:
            _set_keybinding_list([i for i in items if i != KEYBINDING_PATH])
        _quiet(["gsettings", "reset-recursively", f"{KEYBINDING}:{KEYBINDING_PATH}"])
        return True
    schema = f"{KEYBINDING}:{KEYBINDING_PATH}"
    command = f"{shlex.quote(str(paths.MAIN_CMD))} loader"
    ok = True
    for key, value in (("name", "Claude Loader"), ("command", command), ("binding", accel)):
        r = _quiet(["gsettings", "set", schema, key, _gvariant_str(value)])
        ok = ok and bool(r and r.returncode == 0)
    if ok and KEYBINDING_PATH not in items:
        ok = _set_keybinding_list(items + [KEYBINDING_PATH])
    return ok


def hotkey_conflicts(accel: str) -> List[str]:
    """Names of other custom shortcuts already using this key combination."""
    conflicts = []
    for item in _keybinding_list() or []:
        if item == KEYBINDING_PATH:
            continue
        schema = f"{KEYBINDING}:{item}"
        r = _quiet(["gsettings", "get", schema, "binding"])
        if r and r.returncode == 0 and r.stdout.strip().strip("'").lower() == accel.lower():
            n = _quiet(["gsettings", "get", schema, "name"])
            conflicts.append(n.stdout.strip().strip("'") if n else item)
    return conflicts


# --- apply / remove everything -----------------------------------------------------------

def apply(cfg, messages=None) -> List[str]:
    """Bring all generated files and settings in line with the config.

    Returns a list of warnings for things that could not be set up.
    """
    warnings = [] if messages is None else messages
    for p in cfg.profiles:
        if not p.system_default:
            Path(p.data_dir).mkdir(parents=True, exist_ok=True)
    build_icons(cfg)
    write_profile_entries(cfg)
    write_loader_entry(cfg)
    write_usage_entry(cfg)
    write_cli_wrappers(cfg)
    write_autostart(cfg)

    if cfg.loader.enabled and cfg.loader.hotkey:
        if not set_hotkey(cfg.loader.hotkey):
            warnings.append("Could not register the hotkey (is this a GNOME session?). "
                            "You can add it by hand in Settings > Keyboard > Custom Shortcuts "
                            f"with the command: {paths.MAIN_CMD} loader")
    else:
        set_hotkey(None)

    if cfg.url_handler:
        if not enable_url_handler(cfg):
            warnings.append("Could not set the claude:// link handler (xdg-mime not found?).")
    else:
        disable_url_handler(cfg)

    refresh_desktop_database()
    return warnings


def remove_all(cfg) -> None:
    """Undo everything apply() did. Profile data folders are not touched."""
    set_hotkey(None)
    if cfg:
        disable_url_handler(cfg)
    entries = list(APPLICATIONS_DIR.glob("claude-profile*.desktop"))
    entries += [APPLICATIONS_DIR / LOADER_ENTRY, APPLICATIONS_DIR / USAGE_ENTRY,
                AUTOSTART_FILE]
    for f in entries:
        if not f.exists():
            continue
        try:
            if MARKER in f.read_text(encoding="utf-8", errors="ignore"):
                f.unlink()
        except OSError:
            pass
    if paths.BIN_DIR.exists():
        for f in paths.BIN_DIR.glob("claude-*"):
            try:
                if f.is_file() and WRAPPER_MARKER in f.read_text(encoding="utf-8", errors="ignore"):
                    f.unlink()
            except (OSError, UnicodeDecodeError):
                pass
    if paths.ICON_DIR.exists():
        shutil.rmtree(paths.ICON_DIR)
    refresh_desktop_database()
